FROM mcr.microsoft.com/dotnet/sdk:7.0 AS build-env
WORKDIR /app

COPY . ./

# Remove other microservice's and test projects
RUN find src/ -name "*.csproj" \
    ! -path "src/PetProfileDomain/*" \
    ! -path "src/PetAdoptionApp.SharedKernel/*" \
    -exec dotnet sln remove {} \;

RUN dotnet restore

COPY . ./
RUN dotnet publish src/PetProfileDomain/PetProfileDomain.Api/PetProfileDomain.Api.csproj -c Release -o /app/publish

# Runtime image
FROM mcr.microsoft.com/dotnet/aspnet:7.0
RUN apt-get update && \
    apt-get install -y \
        curl \
        dnsutils \
    && rm -rf /var/lib/apt/lists/*
WORKDIR /app
COPY --from=build-env /app/publish ./
ENTRYPOINT ["dotnet", "PetProfileDomain.Api.dll"]