apiVersion: {{ include "common.capabilities.deployment.apiVersion" . }}
kind: Deployment
metadata:
  name: {{ template "common.names.fullname" . }}-petdomain
  namespace: {{ .Release.Namespace | quote }}
  labels: {{- include "common.labels.standard" . | nindent 4 }}
    app.kubernetes.io/component: petdomain
    {{- if .Values.petdomain.commonLabels }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
spec:
  replicas: {{ .Values.petdomain.replicaCount }}
  {{- if .Values.petdomain.updateStrategy }}
  strategy: {{- toYaml .Values.petdomain.updateStrategy | nindent 4 }}
  {{- end }}
  selector:
    matchLabels: {{- include "common.labels.matchLabels" . | nindent 6 }}
      app.kubernetes.io/component: petdomain
  template:
    metadata:
      annotations:
        checksum/configmap: {{ include (print $.Template.BasePath "/petdomain/configmap.yaml") . | sha256sum }}
        {{- if .Values.petdomain.podAnnotations }}
        {{- include "common.tplvalues.render" (dict "value" .Values.petdomain.podAnnotations "context" $) | nindent 8 }}
        {{- end }}
      labels: {{- include "common.labels.standard" . | nindent 8 }}
        app.kubernetes.io/component: petdomain
        {{- if .Values.petdomain.podLabels }}
        {{- include "common.tplvalues.render" (dict "value" .Values.petdomain.podLabels "context" $) | nindent 8 }}
        {{- end }}
    spec:
      serviceAccountName: {{ template "petdomain.serviceAccountName" . }}-petdomain
      {{- include "petdomain.imagePullSecrets" . | nindent 6 }}
      {{- if .Values.petdomain.hostAliases }}
      hostAliases: {{- include "common.tplvalues.render" (dict "value" .Values.petdomain.hostAliases "context" $) | nindent 8 }}
      {{- end }}
      {{- if .Values.petdomain.affinity }}
      affinity: {{- include "common.tplvalues.render" ( dict "value" .Values.petdomain.affinity "context" $) | nindent 8 }}
      {{- else }}
      affinity:
        podAffinity: {{- include "common.affinities.pods" (dict "type" .Values.petdomain.podAffinityPreset "component" "petdomain" "context" $) | nindent 10 }}
        podAntiAffinity: {{- include "common.affinities.pods" (dict "type" .Values.petdomain.podAntiAffinityPreset "component" "petdomain" "context" $) | nindent 10 }}
        nodeAffinity: {{- include "common.affinities.nodes" (dict "type" .Values.petdomain.nodeAffinityPreset.type "key" .Values.petdomain.nodeAffinityPreset.key "values" .Values.petdomain.nodeAffinityPreset.values) | nindent 10 }}
      {{- end }}
      {{- if .Values.petdomain.nodeSelector }}
      nodeSelector: {{- include "common.tplvalues.render" ( dict "value" .Values.petdomain.nodeSelector "context" $) | nindent 8 }}
      {{- end }}
      {{- if .Values.petdomain.tolerations }}
      tolerations: {{- include "common.tplvalues.render" (dict "value" .Values.petdomain.tolerations "context" .) | nindent 8 }}
      {{- end }}
      {{- if .Values.petdomain.schedulerName }}
      schedulerName: {{ .Values.petdomain.schedulerName }}
      {{- end }}
      {{- if .Values.petdomain.topologySpreadConstraints }}
      topologySpreadConstraints: {{- include "common.tplvalues.render" (dict "value" .Values.petdomain.topologySpreadConstraints "context" .) | nindent 8 }}
      {{- end }}
      {{- if .Values.petdomain.priorityClassName }}
      priorityClassName: {{ .Values.petdomain.priorityClassName | quote }}
      {{- end }}
      {{- if .Values.petdomain.podSecurityContext.enabled }}
      securityContext: {{- omit .Values.petdomain.podSecurityContext "enabled" | toYaml | nindent 8 }}
      {{- end }}
      {{- if .Values.petdomain.initContainers }}
      initContainers: {{- include "common.tplvalues.render" (dict "value" .Values.petdomain.initContainers "context" $) | nindent 8 }}
      {{- end }}
      containers:
        - name: petdomain
          image: {{ template "petdomain.image" . }}
          imagePullPolicy: {{ .Values.petdomain.image.pullPolicy }}
          {{- if .Values.petdomain.containerSecurityContext.enabled }}
          securityContext: {{- omit .Values.petdomain.containerSecurityContext "enabled" | toYaml | nindent 12 }}
          {{- end }}
          {{- if .Values.petdomain.containerPorts }}
          ports: {{- include "common.tplvalues.render" (dict "value" .Values.petdomain.containerPorts "context" $) | nindent 12 }}
          {{- end }}
          {{- if .Values.petdomain.diagnosticMode.enabled }}
          command: {{- include "common.tplvalues.render" (dict "value" .Values.petdomain.diagnosticMode.command "context" $) | nindent 12 }}
          {{- else if .Values.petdomain.command }}
          command: {{- include "common.tplvalues.render" (dict "value" .Values.petdomain.command "context" $) | nindent 12 }}
          {{- end }}
          {{- if .Values.petdomain.diagnosticMode.enabled }}
          args: {{- include "common.tplvalues.render" (dict "value" .Values.petdomain.diagnosticMode.args "context" $) | nindent 12 }}
          {{- else if .Values.petdomain.args }}
          args: {{- include "common.tplvalues.render" (dict "value" .Values.petdomain.args "context" $) | nindent 12 }}
          {{- end }}
          env:
            {{- if .Values.petdomain.extraEnvVars }}
            {{- include "common.tplvalues.render" (dict "value" .Values.petdomain.extraEnvVars "context" $) | nindent 12 }}
            {{- end }}
          envFrom:
            {{- if .Values.petdomain.extraEnvVarsCM }}
            - configMapRef:
                name: {{ include "common.tplvalues.render" (dict "value" .Values.petdomain.extraEnvVarsCM "context" $) }}
            {{- end }}
            {{- if .Values.petdomain.extraEnvVarsSecret }}
            - secretRef:
                name: {{ include "common.tplvalues.render" (dict "value" .Values.petdomain.extraEnvVarsSecret "context" $) }}
            {{- end }}
          {{- if .Values.petdomain.resources }}
          resources: {{- toYaml .Values.petdomain.resources | nindent 12 }}
          {{- end }}
          {{- if not .Values.petdomain.diagnosticMode.enabled }}
          {{- if .Values.petdomain.customStartupProbe }}
          startupProbe: {{- include "common.tplvalues.render" (dict "value" .Values.petdomain.customStartupProbe "context" $) | nindent 12 }}
          {{- else if .Values.petdomain.startupProbe.enabled }}
          startupProbe:
            httpGet:
              path: /-/healthy
              port: http
              scheme: HTTP
            initialDelaySeconds: {{ .Values.petdomain.startupProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.petdomain.startupProbe.periodSeconds }}
            timeoutSeconds: {{ .Values.petdomain.startupProbe.timeoutSeconds }}
            successThreshold: {{ .Values.petdomain.startupProbe.successThreshold }}
            failureThreshold: {{ .Values.petdomain.startupProbe.failureThreshold }}
          {{- end }}
          {{- if .Values.petdomain.customLivenessProbe }}
          livenessProbe: {{- include "common.tplvalues.render" (dict "value" .Values.petdomain.customLivenessProbe "context" $) | nindent 12 }}
          {{- else if .Values.petdomain.livenessProbe.enabled }}
          livenessProbe:
            httpGet:
              path: /-/healthy
              port: http
              scheme: HTTP
            initialDelaySeconds: {{ .Values.petdomain.livenessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.petdomain.livenessProbe.periodSeconds }}
            timeoutSeconds: {{ .Values.petdomain.livenessProbe.timeoutSeconds }}
            successThreshold: {{ .Values.petdomain.livenessProbe.successThreshold }}
            failureThreshold: {{ .Values.petdomain.livenessProbe.failureThreshold }}
          {{- end }}
          {{- if .Values.petdomain.customReadinessProbe }}
          readinessProbe: {{- include "common.tplvalues.render" (dict "value" .Values.petdomain.customReadinessProbe "context" $) | nindent 12 }}
          {{- else if .Values.petdomain.readinessProbe.enabled }}
          readinessProbe:
            httpGet:
              path: /-/healthy
              port: http
              scheme: HTTP
            initialDelaySeconds: {{ .Values.petdomain.readinessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.petdomain.readinessProbe.periodSeconds }}
            timeoutSeconds: {{ .Values.petdomain.readinessProbe.timeoutSeconds }}
            successThreshold: {{ .Values.petdomain.readinessProbe.successThreshold }}
            failureThreshold: {{ .Values.petdomain.readinessProbe.failureThreshold }}
          {{- end }}
          {{- if .Values.petdomain.lifecycleHooks }}
          lifecycle: {{- include "common.tplvalues.render" (dict "value" .Values.petdomain.lifecycleHooks "context" $) | nindent 12 }}
          {{- end }}
          {{- end }}
          volumeMounts:
            - name: petdomain-conf
              mountPath: /app/appsettings.json
              subPath: appsettings.json
          {{- if .Values.petdomain.extraVolumeMounts }}
          {{- include "common.tplvalues.render" (dict "value" .Values.petdomain.extraVolumeMounts "context" $) | nindent 12 }}
          {{- end }}
        {{- if .Values.petdomain.sidecars }}
        {{- include "common.tplvalues.render" ( dict "value" .Values.petdomain.sidecars "context" $) | nindent 8 }}
        {{- end }}
      volumes:
        - name: petdomain-conf
          configMap:
            name: {{ template "common.names.fullname" . }}-petdomain-configmap
        {{- if .Values.petdomain.extraVolumes }}
        {{- include "common.tplvalues.render" (dict "value" .Values.petdomain.extraVolumes "context" $) | nindent 8 }}
        {{- end }}
